### ISSUE TITLE
Error trying to deserialize OTA_HotelAvailRQ

### ISSUE THREAD

**Issue by carnau** [goetas-webservices/soap-client-demo#2]
Hello,

I'm trying to use the demo with a custom wsdl, but got error when deserializing the OTA_HotelAvailRQ message. Seems that it's not handling the soap headers as expected. Can you give me some thoughts on what is happening? Thank you.

I attach wsdl and xml message.

[wsdl.tar.gz](https://github.com/goetas-webservices/soap-client-demo/files/654878/wsdl.tar.gz)

[OTA_HotelAvailRQ.txt](https://github.com/goetas-webservices/soap-client-demo/files/654880/OTA_HotelAvailRQ.txt)

Code executed:
`$xml = file_get_contents(__DIR__ . '/OTA_HotelAvailRQ.xml');`
`$test = $serializer->deserialize($xml, ReadRoomTypeCodesInput::class, 'xml');`

CLI Response
`
carnau@lenovo:/srv/host/gitlab/carnau/soap-client-demo$ php bin/demo-server.php 
PHP Fatal error:  Uncaught ReflectionException: Class GoetasWebservices\SoapServices\SoapEnvelope\Headers does not exist in /srv/host/gitlab/carnau/soap-client-demo/vendor/jms/metadata/src/Metadata/MetadataFactory.php:167
Stack trace:
#0 /srv/host/gitlab/carnau/soap-client-demo/vendor/jms/metadata/src/Metadata/MetadataFactory.php(167): ReflectionClass->__construct('GoetasWebservic...')
#1 /srv/host/gitlab/carnau/soap-client-demo/vendor/jms/metadata/src/Metadata/MetadataFactory.php(72): Metadata\MetadataFactory->getClassHierarchy('GoetasWebservic...')
`

**Comment by goetas** [comment]
Can you share the content of `bin/demo-server.php` ?

Do not forget to add the header handler as :

```php
use GoetasWebservices\SoapServices\SoapClient\Arguments\Headers\Handler\HeaderHandler;

$headerHandler =  new HeaderHandler();
$serializer = SoapContainerBuilder::createSerializerBuilderFromContainer($container, function($h){
    $h->registerSubscribingHandler($headerHandler);
})->build();

```

An example is available in the test suite as https://github.com/goetas-webservices/soap-client/blob/master/tests/Client/ClientRequestResponsesTest.php#L66

**Comment by carnau** [comment]
Sure, I added the lambda function with the HeaderHandler but got the same error.

 `PHP Fatal error:  Uncaught ReflectionException: Class GoetasWebservices\SoapServices\SoapEnvelope\Headers does not exist in /srv/host/gitlab/carnau/soap-client-demo/vendor/jms/metadata/src/Metadata/MetadataFactory.php:167`

[demo-server.txt](https://github.com/goetas-webservices/soap-client-demo/files/654952/demo-server.txt)

**Comment by goetas** [comment]
in the generated YAML metadata, do you have some reference to the string`GoetasWebservices\SoapServices\SoapEnvelope\Headers` ?

**Comment by carnau** [comment]
Yes I do, for example in the file SoapEnvelope.Headers.UpdateRatesInput.yml.

```yaml
Example\ExampleBundle\Soap\HotelServices\SoapEnvelope\Headers\UpdateRatesInput:
    xml_namespaces:
        SOAP: 'http://schemas.xmlsoap.org/soap/envelope/'
    properties:
        security:
            expose: true
            access_type: public_method
            accessor:
                getter: getSecurity
                setter: setSecurity
            xml_element:
                namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
            serialized_name: Security
            type: 'GoetasWebservices\SoapServices\SoapEnvelope\Headers<''Example\ExampleBundle\Soap\Security\Secext\Security''>
```
