### ISSUE TITLE
Unable to determine location to save PHP class

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client-demo#3]
I have this in my config.yml:
```yml
soap_client: ~

  xsd2php:
  namespaces:
    'http://tempuri.org/': 'Igm/SoapServices/Calculator'
  destinations_php:
    'Igm/SoapServices/Calculator': src/Calculator
  destinations_jms:
    'Igm/SoapServices/Calculator': metadata/Calculator
wsdl2php:
  metadata:
    'http://www.dneonline.com/calculator.asmx?WSDL': ~**
```

In my composer i have also this: 
```
"autoload" : {
		"psr-4" : {
			"Igm\\SoapServices\\": "src",
			"Igm\\SoapServices\\Calculator"  : "src/Calculator",
			"Service\\"			 : "src/Service"
		}
	}
```
But when I execute the command, return this error: 

php bin/soap-client.php -vvv generate config/config.yml src/Service/Container 

```
 **[GoetasWebservices\Xsd\XsdToPhp\PathGenerator\PathGeneratorException]                                     
  Unable to determine location to save PHP class 'Igm\SoapServices\Calculator\SoapEnvelope\Parts\AddInput'**
```

And when I put a unique  namespace it works well.

**Comment by goetas** [comment]
Pay attention to the file path slashes and php namespace slashes. Your config file should be:

```yml
soap_client: ~

  xsd2php:
  namespaces:
    'http://tempuri.org/': 'Igm\SoapServices\Calculator'
  destinations_php:
    'Igm\SoapServices\Calculator': src/Calculator
  destinations_jms:
    'Igm\SoapServices\Calculator': metadata/Calculator
wsdl2php:
  metadata:
    'http://www.dneonline.com/calculator.asmx?WSDL': ~
```
