### ISSUE TITLE
You must define a type 

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client-demo#4]
I move this my issue in soap-server because the same happens to me. 

```php
$container = new \Igm\SoapServices\Service\Container\SoapClientContainer();

$buildSerializer = $generator::createSerializerBuilderFromContaioner($container, function($h) use($headerHandler){
    $h->registerSubscribingHandler($headerHandler); })->build();
$metadata = $container->get('goetas_webservices.soap_client.metadata_reader');
```

My serializer have the metadatasDir: 
```
      [0] => JMS\Serializer\Metadata\Driver\YamlDriver Object
                        (
                            [locator:Metadata\Driver\AbstractFileDriver:private] => Metadata\Driver\FileLocator Object
                                (
                                    [dirs:Metadata\Driver\FileLocator:private] => Array
                                        (
                                            [Igm\SoapServices\Test] => metadata/Test
                                            [GoetasWebservices\SoapServices\SoapCommon\SoapEnvelope] => /var/www/synergy-generator/src/Generator/../Resources/metadata/jms
                                        )

                                )

                        )
```
My Yml is this: 
```yml
Igm\SoapServices\Test\SoapEnvelope\Messages\GetSimpleInput:
    xml_root_name: 'SOAP:Envelope'
    xml_root_namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
    xml_namespaces:
        SOAP: 'http://schemas.xmlsoap.org/soap/envelope/'
    properties:
        body:
            expose: true
            access_type: public_method
            type: Igm\SoapServices\Test\SoapEnvelope\Parts\GetSimpleInput
            serialized_name: Body
            xml_element:
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
            accessor:
                getter: getBody
                setter: setBody
        header:
            expose: true
            access_type: public_method
            type: GoetasWebservices\SoapServices\SoapClient\Arguments\Headers\Handler\HeaderPlaceholder
            serialized_name: Header
            xml_element:
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
            accessor:
                getter: getHeader
                setter: setHeader

```
But I still have the same error:

You must define a type for Igm\SoapServices\Test\SoapEnvelope\Messages\GetSimpleInput::$body.
