### ISSUE TITLE
This package only run on cli?

### ISSUE THREAD

**Issue by oneword** [goetas-webservices/soap-client-demo#9]
I clone this project to my mac,use ```php bin/demo.php```it run,but when I use ````http://localhost/projectpath/bin/demo.php```` to visit，it is error, look like ````Fatal error: Uncaught JMS\Serializer\Exception\InvalidArgumentException: The directory "metadata/Calculator" does not exist. in /Users/path/projectpath/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php:314 ````

My config.yml is your demo:
````
soap_client:
  #  alternative_endpoints:
  #    service:
  #      port: http://localhost:8080
  namespaces:
    'http://tempuri.org/': 'Calculator'

  destinations_php:
    'Calculator': src/Calculator

  destinations_jms:
    'Calculator': metadata/Calculator
  metadata:
    'http://www.dneonline.com/calculator.asmx?WSDL': ~
````
and I run ````endor/bin/soap-client generate config/config.yml src/Service/Container --dest-class=Service/Container/SoapContainer````

Could I ask you how to run on website?
Thankyou very much.
